server.port=9090
spring.application.name=api-gateway

# Automatically create routes for every service registered in Eureka
spring.cloud.gateway.discovery.locator.enabled=true

# Use lowercase service names in URLs  e.g. /account-service/... instead of /ACCOUNT-SERVICE/...
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Eureka location
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
